name: Terraform CI Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  terraform-checks:
    name: Terraform Lint & Validation
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Format Check
      run: |
        cd terraform-manifests
        terraform fmt -check -recursive

    - name: Terraform Init
      run: |
        cd terraform-manifests
        terraform init -backend-config=../terraform-manifests/env/dev.env -reconfigure

    - name: Terraform Validate
      run: |
        cd terraform-manifests
        terraform validate