name: Azure Bootstrap and Deploy

on:
  push:
    branches:
      - dev
      - qa
      - staging
      - prod
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev, qa, staging, prod)"
        required: false

jobs:
  bootstrap-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set TF_ENV variable
        id: setenv
        run: |
          if [[ -n "${{ github.event.inputs.environment }}" ]]; then
            echo "TF_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "dev" ]]; then
            echo "TF_ENV=dev" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "qa" ]]; then
            echo "TF_ENV=qa" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "staging" ]]; then
            echo "TF_ENV=staging" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "master" ]]; then
            echo "TF_ENV=prod" >> $GITHUB_ENV
          else
            echo "TF_ENV=dev" >> $GITHUB_ENV
          fi

      - name: Show selected environment
        run: |
          echo "Running for environment: $TF_ENV"

      - name: Load environment vars
        run: |
          echo "Loading env/${TF_ENV}.env"
          cat env/${TF_ENV}.env >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Bootstrap backend infrastructure
        run: ./scripts/bootstrap.sh $TF_ENV
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          LOCATION: ${{ env.LOCATION }}

      - name: Terraform Init
        run: terraform -chdir=terraform-manifests init \
          -backend-config="resource_group_name=rg-${TF_ENV}-tfstate" \
          -backend-config="storage_account_name=st${TF_ENV}tfstate001" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=${TF_ENV}.tfstate"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Apply
        run: terraform -chdir=terraform-manifests apply -var="environment=$TF_ENV" -var-file="${TF_ENV}.tfvars" -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
