name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy (dev, qa, prod)'
        required: true
        default: 'dev'

jobs:
  terraform:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: |
        cd terraform-manifests
        terraform init -backend-config=../terraform-manifests/env/${{ github.event.inputs.environment }}.env -reconfigure

    - name: Terraform Destroy
      run: |
        cd terraform-manifests
        terraform destroy -auto-approve -var-file="${{ github.event.inputs.environment }}.tfvars"